name: inventory_srv
host: 10.8.117.74
tags:
  - inventory_srv
  - dev
  - alan
mysql:
  host: "172.26.25.139"
  port: 30006
  db: "mxshop_inventory_srv"
  user: "root"
  password: "admin123"
consul:
  host: "172.26.25.139"
  port: 30500
redis:
  host: 172.26.25.139
  port: 30079
  password: admin123
  expire: 300