name: userop_srv
host: 10.8.117.74
tags:
  - userop_srv
  - dev
  - alan
mysql:
  host: "172.26.25.139"
  port: 30006
  db: "mxshop_userop_srv"
  user: "root"
  password: "admin123"
consul:
  host: "172.26.25.139"
  port: 30500