name: goods_srv
host: 10.8.117.74
tags:
  - goods_srv
  - dev
  - alan
mysql:
  host: "172.26.25.139"
  port: 30006
  db: "mxshop_goods_srv"
  user: "root"
  password: "admin123"
consul:
  host: "172.26.25.139"
  port: 30500
es:
  host: "172.26.25.139"
  port: 32000