name: user_srv
host: 100.200.27.114
tags:
  - user_srv
  - dev
  - alan
mysql:
  host: "172.26.25.139"
  port: 30006
  db: "mxshop_user_srv"
  user: "root"
  password: "admin123"
consul:
  host: "172.26.25.139"
  port: 30500